run:
	python -m manim src/new_contract.py OpeningManim
	python -m manim src/collaboration.py Collaboration
	python -m manim src/contract.py Contract
	python -m manim src/develop.py Develop
	python -m manim src/no_litige.py NoLitigation
	python -m manim src/litige.py Litigation

viz:
	open media/videos/new_contract/480p15/OpeningManim.mp4
	open media/videos/collaboration/480p15/Collaboration.mp4
	open media/videos/contract/480p15/Contract.mp4
	open media/videos/develop/480p15/Develop.mp4
	open media/videos/no_litige/480p15/NoLitigation.mp4
	open media/videos/litige/480p15/Litigation.mp4

interactive:
	python -m manim src/contract.py Contract