run:
	#python -m manim src/new_contract.py OpeningManim -ql
	#python -m manim src/collaboration.py Collaboration -ql
	python -m manim src/contract.py Contract -ql

viz:
	#open media/videos/new_contract/480p15/OpeningManim.mp4
	#open media/videos/collaboration/480p15/Collaboration.mp4
	open media/videos/contract/480p15/Contract.mp4

interactive:
	python -m manim src/contract.py Contract